services:
  - type: web
    name: studyme
    env: node
    buildCommand: |
      npm install
      python3 -m pip install --upgrade yt-dlp
    startCommand: node server.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false